@startuml
class "PHARE::amr::FieldOverlap" as YzpATkBQSEFSRUBOQGFtckBTQEZpZWxkT3ZlcmxhcA
class "PHARE::amr::Hierarchy" as YzpATkBQSEFSRUBOQGFtckBTQEhpZXJhcmNoeQ
class "PHARE::amr::HybridMessengerInfo" as YzpATkBQSEFSRUBOQGFtckBTQEh5YnJpZE1lc3NlbmdlckluZm8 << (I, LightBlue) >>
class "PHARE::amr::AFieldGeometry" as YzpATkBQSEFSRUBOQGFtckBTQEFGaWVsZEdlb21ldHJ5
class "PHARE::amr::FieldFillPattern" as YzpATkBQSEFSRUBOQGFtckBTQEZpZWxkRmlsbFBhdHRlcm4
class "PHARE::core::MaxwellianInitFunctions" as YzpATkBQSEFSRUBOQGNvcmVAU0BNYXh3ZWxsaWFuSW5pdEZ1bmN0aW9ucw
class "PHARE::StreamAppender" as YzpATkBQSEFSRUBTQFN0cmVhbUFwcGVuZGVy
class "PHARE::amr::CoarsenWeighter" as YzpATkBQSEFSRUBOQGFtckBTQENvYXJzZW5XZWlnaHRlcg
class "PHARE::amr::LinearWeighter" as YzpATkBQSEFSRUBOQGFtckBTQExpbmVhcldlaWdodGVy
class "PHARE::amr::MHDMessengerInfo" as YzpATkBQSEFSRUBOQGFtckBTQE1IRE1lc3NlbmdlckluZm8 << (I, LightBlue) >>
class "PHARE::amr::Tagger" as YzpATkBQSEFSRUBOQGFtckBTQFRhZ2dlcg << (A, Pink) >>
class "PHARE::core::ConstantTimeStamper" as YzpATkBQSEFSRUBOQGNvcmVAU0BDb25zdGFudFRpbWVTdGFtcGVy
class "PHARE::core::Errors" as YzpATkBQSEFSRUBOQGNvcmVAU0BFcnJvcnM
class "PHARE::core::MHDStateInitializer" as YzpATkBQSEFSRUBOQGNvcmVAU0BNSERTdGF0ZUluaXRpYWxpemVy
class "PHARE::initializer::PHAREDictHandler" as YzpATkBQSEFSRUBOQGluaXRpYWxpemVyQFNAUEhBUkVEaWN0SGFuZGxlcg
class "PHARE::ISimulator" as YzpATkBQSEFSRUBTQElTaW11bGF0b3I << (A, Pink) >>
class "PHARE::SamraiLifeCycle" as YzpATkBQSEFSRUBTQFNhbXJhaUxpZmVDeWNsZQ
class "PHARE::amr::AFieldRefineOperator" as YzpATkBQSEFSRUBOQGFtckBTQEFGaWVsZFJlZmluZU9wZXJhdG9y
class "PHARE::amr::IMessengerInfo" as YzpATkBQSEFSRUBOQGFtckBTQElNZXNzZW5nZXJJbmZv << (I, LightBlue) >>
class "PHARE::amr::VecFieldDescriptor" as YzpATkBQSEFSRUBOQGFtckBTQFZlY0ZpZWxkRGVzY3JpcHRvcg
class "PHARE::core::HybridQuantity" as YzpATkBQSEFSRUBOQGNvcmVAU0BIeWJyaWRRdWFudGl0eQ
class "PHARE::core::IPhysicalState" as YzpATkBQSEFSRUBOQGNvcmVAU0BJUGh5c2ljYWxTdGF0ZQ
class "PHARE::core::ITimeStamper" as YzpATkBQSEFSRUBOQGNvcmVAU0BJVGltZVN0YW1wZXI
class "PHARE::core::MeshToParticle" as YzpATkBQSEFSRUBOQGNvcmVAU0BNZXNoVG9QYXJ0aWNsZT4jVmwy
class "PHARE::core::MeshToParticle" as YzpATkBQSEFSRUBOQGNvcmVAU0BNZXNoVG9QYXJ0aWNsZT4jVmwx
class "PHARE::core::MeshToParticle" as YzpATkBQSEFSRUBOQGNvcmVAU0BNZXNoVG9QYXJ0aWNsZT4jVmwz
class "PHARE::core::NdArrayMask" as YzpATkBQSEFSRUBOQGNvcmVAU0BOZEFycmF5TWFzaw
class "PHARE::core::ParticleToMesh" as YzpATkBQSEFSRUBOQGNvcmVAU0BQYXJ0aWNsZVRvTWVzaD4jVmwy
class "PHARE::core::ParticleToMesh" as YzpATkBQSEFSRUBOQGNvcmVAU0BQYXJ0aWNsZVRvTWVzaD4jVmwz
class "PHARE::core::ParticleToMesh" as YzpATkBQSEFSRUBOQGNvcmVAU0BQYXJ0aWNsZVRvTWVzaD4jVmwx
class "PHARE::core::PhysicalStateInitializer" as YzpATkBQSEFSRUBOQGNvcmVAU0BQaHlzaWNhbFN0YXRlSW5pdGlhbGl6ZXI
class "PHARE::core::PusherFactory" as YzpATkBQSEFSRUBOQGNvcmVAU0BQdXNoZXJGYWN0b3J5
class "PHARE::core::Weighter" as YzpATkBQSEFSRUBOQGNvcmVAU0BXZWlnaHRlcj4jVmwz
class "PHARE::core::Weighter" as YzpATkBQSEFSRUBOQGNvcmVAU0BXZWlnaHRlcj4jVmwx
class "PHARE::core::Weighter" as YzpATkBQSEFSRUBOQGNvcmVAU0BXZWlnaHRlcj4jVmwy
class "PHARE::diagnostic::IDiagnosticsManager" as YzpATkBQSEFSRUBOQGRpYWdub3N0aWNAU0BJRGlhZ25vc3RpY3NNYW5hZ2Vy << (I, LightBlue) >>
class "PHARE::initializer::DataProvider" as YzpATkBQSEFSRUBOQGluaXRpYWxpemVyQFNARGF0YVByb3ZpZGVy << (I, LightBlue) >>
class "PHARE::initializer::PHAREDict" as YzpATkBzdGRATkBfX2N4eDExQFNAYmFzaWNfc3RyaW5nPiNDIyRATkBzdGRAU0BjaGFyX3RyYWl0cz4jQyMkQE5Ac3RkQFNAYWxsb2NhdG9yPiND
class "PHARE::solver::MessengerRegistration" as YzpATkBQSEFSRUBOQHNvbHZlckBTQE1lc3NlbmdlclJlZ2lzdHJhdGlvbg
class "SAMRAI::hier::Box" as YzpATkBTQU1SQUlATkBoaWVyQFNAQm94
class "SAMRAI::hier::BoxContainer" as YzpATkBTQU1SQUlATkBoaWVyQFNAQm94Q29udGFpbmVy
class "SAMRAI::hier::BoxGeometry" as YzpATkBTQU1SQUlATkBoaWVyQFNAQm94R2VvbWV0cnk
class "SAMRAI::hier::BoxOverlap" as YzpATkBTQU1SQUlATkBoaWVyQFNAQm94T3ZlcmxhcA
class "SAMRAI::hier::PatchHierarchy" as YzpATkBTQU1SQUlATkBoaWVyQFNAUGF0Y2hIaWVyYXJjaHk
class "SAMRAI::hier::Transformation" as YzpATkBTQU1SQUlATkBoaWVyQFNAVHJhbnNmb3JtYXRpb24
class "SAMRAI::tbox::Logger::Appender" as YzpATkBTQU1SQUlATkB0Ym94QFNATG9nZ2VyQFNAQXBwZW5kZXI
class "SAMRAI::xfer::VariableFillPattern" as YzpATkBTQU1SQUlATkB4ZmVyQFNAVmFyaWFibGVGaWxsUGF0dGVybg
class "std::array<std::shared_ptr<PHARE::core::Span<double, unsigned long>>, 3>" as YzpATkBzdGRAU0BhcnJheT4jJEBOQHN0ZEBTQHNoYXJlZF9wdHI-IyRATkBQSEFSRUBOQGNvcmVAU0BTcGFuPiNkI2wjVmwz
class "std::optional<bool>" as YzpATkBzdGRAU0BvcHRpb25hbD4jYg
class "std::shared_ptr<PHARE::core::Span<double, unsigned long>>" as YzpATkBzdGRAU0BzaGFyZWRfcHRyPiMkQE5AUEhBUkVATkBjb3JlQFNAU3Bhbj4jZCNs
class "std::vector<double, std::allocator<double>>" as YzpATkBzdGRAU0B2ZWN0b3I-I2QjJEBOQHN0ZEBTQGFsbG9jYXRvcj4jZA
class "std::vector<int, std::allocator<int>>" as YzpATkBzdGRAU0B2ZWN0b3I-I0kjJEBOQHN0ZEBTQGFsbG9jYXRvcj4jSQ
"YzpATkBQSEFSRUBOQGFtckBTQEZpZWxkT3ZlcmxhcA" --|> "YzpATkBTQU1SQUlATkBoaWVyQFNAQm94T3ZlcmxhcA"
"YzpATkBQSEFSRUBOQGFtckBTQEZpZWxkT3ZlcmxhcA" *-- "YzpATkBTQU1SQUlATkBoaWVyQFNAVHJhbnNmb3JtYXRpb24"
"YzpATkBQSEFSRUBOQGFtckBTQEZpZWxkT3ZlcmxhcA" *-- "YzpATkBTQU1SQUlATkBoaWVyQFNAQm94Q29udGFpbmVy"
"YzpATkBQSEFSRUBOQGFtckBTQEhpZXJhcmNoeQ" *-- "YzpATkBzdGRAU0B2ZWN0b3I-I0kjJEBOQHN0ZEBTQGFsbG9jYXRvcj4jSQ"
"YzpATkBQSEFSRUBOQGFtckBTQEhpZXJhcmNoeQ" *-- "YzpATkBzdGRAU0B2ZWN0b3I-I2QjJEBOQHN0ZEBTQGFsbG9jYXRvcj4jZA"
"YzpATkBQSEFSRUBOQGFtckBTQEhpZXJhcmNoeQ" --|> "YzpATkBTQU1SQUlATkBoaWVyQFNAUGF0Y2hIaWVyYXJjaHk"
"YzpATkBQSEFSRUBOQGFtckBTQEh5YnJpZE1lc3NlbmdlckluZm8" --|> "YzpATkBQSEFSRUBOQGFtckBTQElNZXNzZW5nZXJJbmZv"
"YzpATkBQSEFSRUBOQGFtckBTQEh5YnJpZE1lc3NlbmdlckluZm8" *-- "YzpATkBQSEFSRUBOQGFtckBTQFZlY0ZpZWxkRGVzY3JpcHRvcg"
"YzpATkBQSEFSRUBOQGFtckBTQEh5YnJpZE1lc3NlbmdlckluZm8" *-- "YzpATkBzdGRATkBfX2N4eDExQFNAYmFzaWNfc3RyaW5nPiNDIyRATkBzdGRAU0BjaGFyX3RyYWl0cz4jQyMkQE5Ac3RkQFNAYWxsb2NhdG9yPiND"
"YzpATkBQSEFSRUBOQGFtckBTQEFGaWVsZEdlb21ldHJ5" --|> "YzpATkBTQU1SQUlATkBoaWVyQFNAQm94R2VvbWV0cnk"
"YzpATkBQSEFSRUBOQGFtckBTQEFGaWVsZEdlb21ldHJ5" *-- "YzpATkBTQU1SQUlATkBoaWVyQFNAQm94"
"YzpATkBQSEFSRUBOQGFtckBTQEZpZWxkRmlsbFBhdHRlcm4" *-- "YzpATkBzdGRAU0BvcHRpb25hbD4jYg"
"YzpATkBQSEFSRUBOQGFtckBTQEZpZWxkRmlsbFBhdHRlcm4" --|> "YzpATkBTQU1SQUlATkB4ZmVyQFNAVmFyaWFibGVGaWxsUGF0dGVybg"
"YzpATkBQSEFSRUBOQGNvcmVAU0BNYXh3ZWxsaWFuSW5pdEZ1bmN0aW9ucw" *-- "YzpATkBzdGRAU0BzaGFyZWRfcHRyPiMkQE5AUEhBUkVATkBjb3JlQFNAU3Bhbj4jZCNs"
"YzpATkBQSEFSRUBOQGNvcmVAU0BNYXh3ZWxsaWFuSW5pdEZ1bmN0aW9ucw" *-- "YzpATkBzdGRAU0BhcnJheT4jJEBOQHN0ZEBTQHNoYXJlZF9wdHI-IyRATkBQSEFSRUBOQGNvcmVAU0BTcGFuPiNkI2wjVmwz"
"YzpATkBQSEFSRUBTQFN0cmVhbUFwcGVuZGVy" --|> "YzpATkBTQU1SQUlATkB0Ym94QFNATG9nZ2VyQFNAQXBwZW5kZXI"
"YzpATkBQSEFSRUBOQGFtckBTQENvYXJzZW5XZWlnaHRlcg" *-- "YzpATkBzdGRAU0B2ZWN0b3I-I2QjJEBOQHN0ZEBTQGFsbG9jYXRvcj4jZA"
"YzpATkBQSEFSRUBOQGFtckBTQExpbmVhcldlaWdodGVy" *-- "YzpATkBzdGRAU0B2ZWN0b3I-I2QjJEBOQHN0ZEBTQGFsbG9jYXRvcj4jZA"
"YzpATkBQSEFSRUBOQGFtckBTQE1IRE1lc3NlbmdlckluZm8" --|> "YzpATkBQSEFSRUBOQGFtckBTQElNZXNzZW5nZXJJbmZv"
"YzpATkBQSEFSRUBOQGFtckBTQFRhZ2dlcg" *-- "YzpATkBzdGRATkBfX2N4eDExQFNAYmFzaWNfc3RyaW5nPiNDIyRATkBzdGRAU0BjaGFyX3RyYWl0cz4jQyMkQE5Ac3RkQFNAYWxsb2NhdG9yPiND"
"YzpATkBQSEFSRUBOQGNvcmVAU0BDb25zdGFudFRpbWVTdGFtcGVy" --|> "YzpATkBQSEFSRUBOQGNvcmVAU0BJVGltZVN0YW1wZXI"
"YzpATkBQSEFSRUBOQGNvcmVAU0BFcnJvcnM" *-- "YzpATkBzdGRATkBfX2N4eDExQFNAYmFzaWNfc3RyaW5nPiNDIyRATkBzdGRAU0BjaGFyX3RyYWl0cz4jQyMkQE5Ac3RkQFNAYWxsb2NhdG9yPiND"
"YzpATkBQSEFSRUBOQGNvcmVAU0BNSERTdGF0ZUluaXRpYWxpemVy" --|> "YzpATkBQSEFSRUBOQGNvcmVAU0BQaHlzaWNhbFN0YXRlSW5pdGlhbGl6ZXI"
"YzpATkBQSEFSRUBOQGluaXRpYWxpemVyQFNAUEhBUkVEaWN0SGFuZGxlcg" *-- "YzpATkBzdGRATkBfX2N4eDExQFNAYmFzaWNfc3RyaW5nPiNDIyRATkBzdGRAU0BjaGFyX3RyYWl0cz4jQyMkQE5Ac3RkQFNAYWxsb2NhdG9yPiND"
@enduml
